services:
  web:
    build: ./
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_started
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: btc
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

volumes:
  db_data: